services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - gyan_bhandar_network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - GROQ_API_KEY=<GROQ_API_KEY>
      - MODEL_PATH=all-MiniLM-L6-v2
    volumes:
      - ./backend/documents:/app/documents
      - ./backend/chat_history:/app/chat_history
      - faiss_data:/app
    networks:
      - gyan_bhandar_network

volumes:
  faiss_data:

networks:
  gyan_bhandar_network:
    driver: bridge