services:
  backend:
    build: ./backend
    container_name: gyaan_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - faiss_data:/app/faiss_store
      - ./backend/documents:/app/documents
      - ./backend/chat_history:/app/chat_history
      - /all-MiniLM-L6-v2:/app/all-MiniLM-L6-v2
    networks:
      - gyan_bhandar_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: gyaan_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - gyan_bhandar_network
    restart: unless-stopped

volumes:
  faiss_data:

networks:
  gyan_bhandar_network:
    driver: bridge