apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gyan-bhandar-backend
  name: gyan-bhandar-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gyan-bhandar-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: gyan-bhandar-backend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - image: kpkm25/gyan-bhandar-backend:latest
        name: gyan-bhandar-backend
        ports:
        - containerPort: 5000
        resources: {}
        envFrom:
          - secretRef:
              name: gyan-secrets
status: {}
