apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gyan-bhandar
  name: gyan-bhandar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gyan-bhandar
  strategy: {}
  template:
    metadata:
      labels:
        app: gyan-bhandar
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - image: kpkm25/gyan-bhandar-frontend:latest
        name: gyan-bhandar
        ports:
        -containerPort: 80
        resources: {}
        envFrom:
          - secretRef:
              name: gyan-secrets
status: {}
