apiVersion: v1
kind: Service
metadata:
  name: gyan-bhandar-backend-svc
  namespace: gyaan-bhandar
  labels:
    app: gyan-bhandar-backend
spec:
  selector:
    app: gyan-bhandar-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      