apiVersion: v1
kind: Service
metadata:
  name: gyan-bhandar-frontend-svc
  namespace: gyaan-bhandar
  labels:
    app: gyan-bhandar-frontend
spec:
  selector:
    app: gyan-bhandar-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      